using ShieldWall.Shared.Enums;

namespace ShieldWall.Shared.Models;

/// <summary>
/// An incoming alert emitted by the sentinel grid during the exercise.
/// This is the primary unit of work that teams must classify and respond to.
/// </summary>
public record SentinelAlert
{
    /// <summary>Unique alert identifier in "SA-NNNN" format (e.g., "SA-0001").</summary>
    public required string AlertId { get; init; }

    /// <summary>UTC timestamp when the alert was generated by the sentinel grid.</summary>
    public required DateTime Timestamp { get; init; }

    /// <summary>Grid sector that produced the alert (e.g., "Alpha-7").</summary>
    public required string Sector { get; init; }

    /// <summary>Category of the alert signal.</summary>
    public required AlertType Type { get; init; }

    /// <summary>Raw severity on a 1–10 scale as reported by the source system.</summary>
    public required int RawSeverity { get; init; }

    /// <summary>
    /// Confidence in the alert signal, in the range 0.0–1.0.
    /// Lower values indicate noisy or unreliable readings.
    /// </summary>
    public required double ConfidenceScore { get; init; }

    /// <summary>Originating data source (e.g., "Radar-North", "CyberSensor-East").</summary>
    public required string Source { get; init; }

    /// <summary>
    /// Optional shared correlation key that links related alerts into a group.
    /// When non-null, multiple alerts with the same value may form a compound threat.
    /// </summary>
    public string? CorrelationGroup { get; init; }

    /// <summary>
    /// Additional contextual metadata provided by the source system.
    /// Common keys: <c>sourceReliability</c>, <c>direction</c>, <c>velocity</c>.
    /// </summary>
    public Dictionary<string, string> Metadata { get; init; } = new();
}
