namespace ShieldWall.Shared.Models;

/// <summary>
/// Full post-exercise performance export for a single team.
/// Generated by the Game Master at the end of the scenario.
/// </summary>
public record TeamResults
{
    /// <summary>The team name.</summary>
    public required string Team { get; init; }

    /// <summary>Overall mission effectiveness percentage at exercise end (0–100).</summary>
    public required double FinalEffectiveness { get; init; }

    /// <summary>Total number of alerts the team submitted decisions for.</summary>
    public required int AlertsProcessed { get; init; }

    /// <summary>Number of alerts for which no decision was submitted before the window closed.</summary>
    public required int AlertsMissed { get; init; }

    /// <summary>Rolling average response latency across all submitted decisions (milliseconds).</summary>
    public required int AverageLatencyMs { get; init; }

    /// <summary>Fraction of alerts classified at the correct threat level (0.0–1.0).</summary>
    public required double ClassificationAccuracy { get; init; }

    /// <summary>Fraction of alerts where the chosen action matched ground truth (0.0–1.0).</summary>
    public required double ActionAccuracy { get; init; }

    /// <summary>Number of compound threats successfully identified by the team.</summary>
    public required int CompoundThreatsDetected { get; init; }

    /// <summary>Total number of compound threats present in the scenario.</summary>
    public required int CompoundThreatsTotal { get; init; }

    /// <summary>
    /// Fraction of <see cref="Enums.ThreatLevel.Noise"/> alerts correctly dismissed (0.0–1.0).
    /// </summary>
    public required double NoiseCorrectlyDismissed { get; init; }

    /// <summary>Per-phase effectiveness breakdown.</summary>
    public IReadOnlyList<PhaseResults> PhaseBreakdown { get; init; } = [];
}
